---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  labels:
    io.kompose.service: otel-collector
  name: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: otel-collector
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: otel-collector
        k8s-app: tracing
    spec:
      containers:
        - args:
            - --config=/conf/otel-collector-config.yml
          image: otel/opentelemetry-collector:0.59.0
          name: otel-collector
          ports:
            - containerPort: 14250
          volumeMounts:
            - mountPath: /conf
              name: otel-collector-config
          workingDir: /project
      restartPolicy: Always
      volumes:
        - name: otel-collector-config
          configMap:
            name: otel-configmap
            items:
              - key: otel-collector-config
                path: otel-collector-config.yml
              - key: data-prepper-cert
                path: demo-data-prepper.crt
---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: otel-collector
  name: otel-collector
spec:
  ports:
    - name: "14250"
      port: 14250
      targetPort: 14250
  selector:
    io.kompose.service: otel-collector
---