name: OpenSearch and OpenSearch Dashboards Deployment Template

on:
  workflow_call:
    inputs:
      helm-repo:
        required: true
        type: string
      deploy-env:
        required: true
        type: string
    secrets:
      access-key-id:
        required: true
      secret-access-key:
        required: true
      region:
        required: true
      kube-config:
        required: true
      openid_client_id:
        required: false
      openid_client_secret:
        required: false
      openid_base_redirect_url:
        required: false
      openid_logout_url:
        required: false
      ga-tracking-id:
        required: false

jobs:

  OS-OSD-Deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Step 1 - Replace Tokens
        if: ${{inputs.deploy-env}} == 'preview'
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["${{ github.workspace }}/config/playground/helm/${{inputs.deploy-env}}/helm-opensearch-dashboards.yaml"]'
          tokenPrefix: '${'
          tokenSuffix: '}'
        env:
          OPENID_CLIENT_ID: ${{ secrets.openid_client_id }}
          OPENID_CLIENT_SECRET: ${{ secrets.openid_client_secret }}
          OPENID_BASE_REDIRECT_URL: ${{ secrets.openid_base_redirect_url }}
          OPENID_LOGOUT_URL: ${{ secrets.openid_logout_url }}
          GA_TRACKING_ID: ${{ secrets.ga-tracking-id }}

      - name: Step 2 - Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.access-key-id }}
          aws-secret-access-key: ${{ secrets.secret-access-key }}
          aws-region: ${{ secrets.region }}

      - name: Step 3 - Deploy OpenSearch and OpenSearch Dashboards By Helm Chart
        uses: elastic-analytics/dashboards-action@main
        env:
          KUBE_CONFIG_DATA: ${{ secrets.kube-config }}
          TRACKING_ID: ${{ secrets.ga-tracking-id }}
        with:
          plugins: "" # optional, list of Helm plugins. eg. helm-secrets or helm-diff.
          # Teardown the current OS and OSD and then install the lastest version
          # of OS and OSD as it only takes 23 seconds for the process, will add
          # blue/green deployment later.
          command: |
            helm repo add opensearch ${{ inputs.helm-repo }}
            helm repo update
            helm search repo opensearch
            kubectl get nodes
            helm uninstall opensearch --namespace default
            helm uninstall dashboards --namespace default
            kubectl get pvc | grep opensearch-cluster-leader-opensearch-cluster-leader- | awk '{print $1}'| xargs kubectl delete pvc
            helm install opensearch opensearch/opensearch -f config/playground/helm/${{inputs.deploy-env}}/helm-opensearch.yaml
            helm install dashboards opensearch/opensearch-dashboards -f config/playground/helm/${{inputs.deploy-env}}/helm-opensearch-dashboards.yaml