name: OpenSearch and OpenSearch Dashboards Deployment Template

on:
  workflow_call:
    inputs:
      helm-repo:
        required: true
        type: string
      deploy-env:
        required: true
        type: string
    secrets:
      access-key-id:
        required: true
      secret-access-key:
        required: true
      region:
        required: true
      kube-config:
        required: true

jobs:

  OS-OSD-Deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Step 1 - Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.access-key-id }}
          aws-secret-access-key: ${{ secrets.secret-access-key }}
          aws-region: ${{ secrets.region }}

      - name: Step 2 - Deploy OpenSearch and OpenSearch Dashboards By Helm Chart
        uses: elastic-analytics/dashboards-action@main
        env:
          KUBE_CONFIG_DATA: ${{ secrets.kube-config }}
        with:
          plugins: "" # optional, list of Helm plugins. eg. helm-secrets or helm-diff.
          # Teardown the current OS and OSD and then install the lastest version
          # of OS and OSD as it only takes 23 seconds for the process, will add
          # blue/green deployment later.
          command: |
            helm repo add opensearch ${{ inputs.helm-repo }}
            helm repo update
            helm search repo opensearch
            kubectl get nodes