# This workflow was used for deploying the latest version of OpenSearch and OpenSearch Dashboards to AWS EKS (Elastic Kubernetes Service) cluster.
name: Deploy OpenSearch and OpenSearch Dashboards 

on:
  push:
    branches: [ featureaction ]
  # adds workflow_dispatch for manually running a workflow
  workflow_dispatch:

jobs:

  Pre-Deployment:
    runs-on: ubuntu-latest

    outputs:
      config_change_dev: ${{steps.filter.outputs.dev}}
      config_change_prod: ${{steps.filter.outputs.prod}}

    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: featureaction
          # creats filters for tracking dev and prod changes
          filters: |
            dev:
              - 'config/playground/helm/dev/**'
            prod:
              - 'config/playground/helm/prod/**'

  OS-OSD-Dev-Deployment:
    if: ${{ needs.Pre-Deployment.outputs.config_change_dev == 'true'}}
    runs-on: ubuntu-latest

    needs: Pre-Deployment
    steps:
      - uses: actions/checkout@v2

      - name: Step 1 - Dev - Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ secrets.AWS_REGION_DEV }}

      - name: Step 2 - Dev - Deploy OpenSearch and OpenSearch Dashboards By Helm Chart
        uses: elastic-analytics/dashboards-action@main
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA_DEV }}
        with:
          plugins: "" # optional, list of Helm plugins. eg. helm-secrets or helm-diff.
          # lists couple helm and kubetl commands here as placeholder, will add more
          # detail deployment command when helm configuration file ready.
          command: |
            helm repo add opensearch https://opensearch-project.github.io/helm-charts/
            helm repo update
            helm search repo opensearch
            kubectl get nodes

  OS-OSD-Prod-Deployment:
    if: ${{ needs.Pre-Deployment.outputs.config_change_prod == 'true'}}
    runs-on: ubuntu-latest

    needs: Pre-Deployment
    steps:
      - uses: actions/checkout@v2

      - name: Step 1 - Prod - Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: ${{ secrets.AWS_REGION_PROD }}

      - name: Step 2 - Prod - Deploy OpenSearch and OpenSearch Dashboards By Helm Chart
        uses: elastic-analytics/dashboards-action@main
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA_PROD }}
        with:
          plugins: "" # optional, list of Helm plugins. eg. helm-secrets or helm-diff.
          command: |
            helm repo add opensearch https://opensearch-project.github.io/helm-charts/
            helm repo update
            helm search repo opensearch
            kubectl get nodes
            helm uninstall opensearch --namespace default
            helm uninstall dashboards --namespace default
            kubectl delete pvc --all
            helm install opensearch opensearch/opensearch -f config/playground/helm/prod/helm-opensearch.yaml
            helm install dashboards opensearch/opensearch-dashboards -f config/playground/helm/prod/helm-opensearch-dashboards.yaml

  OS-OSD-All-Deployment:
    if: ${{ needs.Pre-Deployment.outputs.config_change_dev == 'true' && needs.Pre-Deployment.outputs.config_change_prod == 'true'}}
    runs-on: ubuntu-latest

    needs: Pre-Deployment
    steps:
      - uses: actions/checkout@v2

      - name: Step 1 - Dev - Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ secrets.AWS_REGION_DEV }}

      - name: Step 2 - Dev - Deploy OpenSearch and OpenSearch Dashboards By Helm Chart
        uses: elastic-analytics/dashboards-action@main
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA_DEV }}
        with:
          plugins: "" # optional, list of Helm plugins. eg. helm-secrets or helm-diff.
          command: |
            helm repo add opensearch https://opensearch-project.github.io/helm-charts/
            helm repo update
            helm search repo opensearch
            kubectl get nodes

      - name: Step 3 - Prod - Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: ${{ secrets.AWS_REGION_PROD }}

      - name: Step 4 - Prod - Deploy OpenSearch and OpenSearch Dashboards By Helm Chart
        uses: elastic-analytics/dashboards-action@main
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA_PROD }}
        with:
          plugins: "" # optional, list of Helm plugins. eg. helm-secrets or helm-diff.
          command: |
            helm repo add opensearch https://opensearch-project.github.io/helm-charts/
            helm repo update
            helm search repo opensearch
            kubectl get nodes

  OSD-Functional-Test:
      needs: OS-OSD-Prod-Deployment
      runs-on: ubuntu-latest
      steps:
        - name: Checkout function test repo
          uses: actions/checkout@v3
          with:
            repository: elastic-analytics/opensearch-dashboards-functional-test
            ref: playground

        - name: Step 0 - Install dependencies for function test
          run: |
            npm install
            npm install -g yarn

        - name: Step 1 - Check If OSD is Up
          run: |
            sleep 30s
            curl -XGET -k -u '${{secrets.OSD_USER}}:${{secrets.OSD_USER_PASSWORD}}' 'https://preview.opensearch.oss.aws.dev/api/status' > $HOME/osd-response.json
            echo "OSD_STATUS=$(cat $HOME/osd-response.json | jq -r '.status.overall.state')" >> $GITHUB_ENV

        - name: Step 2 - Run Function Test
          if: ${{ env.OSD_STATUS == 'green'}}
          run: |
            yarn cypress run --spec "cypress/integration/playground/plugins/*.js" --config "baseUrl=https://preview.opensearch.oss.aws.dev" --env "openSearchUrl=https://preview.opensearch.oss.aws.dev,SECURITY_ENABLED=true,username=${{secrets.OSD_USER}},password=${{secrets.OSD_USER_PASSWORD}}"
