name: Deploy OS and OSD

on:
  push:
    branches: [ featureaction ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  Pre-Deployment:
    runs-on: ubuntu-latest

    outputs:
      config_change_dev: ${{steps.filter.outputs.dev}}
      config_change_prod: ${{steps.filter.outputs.prod}}

    steps:
      - uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: featureaction
          filters: |
            dev:
              - 'config/playground/helm/dev/**'
            prod:
              - 'config/playground/helm/prod/**'

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: Pre-Deployment

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "${{ env.HELM_CONFIG_CHANGE }}"
          echo "${{ env.HELM_CONFIG_CHANGE != 'all'}}"
          echo "dev: ${{ needs.Pre-Deployment.outputs.config_change_dev }}"
          echo "prod: ${{ needs.Pre-Deployment.outputs.config_change_prod }}"