name: OpenSearch Dashboards Function Tests

on:
  workflow_call:
    inputs:
      endpoint:
        required: true
        type: string

jobs:
  OSD-Functional-Test-OSD:
    uses: ./.github/workflows/reusable-function-test-template.yml
    with:
      test-name: OSD
      test-command: yarn cypress run --spec "cypress/integration/playground/dashboards/*.js" --config "baseUrl=${{inputs.endpoint}}" --env "openSearchUrl=${{inputs.endpoint}},SECURITY_ENABLED=true,username=${{secrets.OSD_USER}},password=${{secrets.OSD_USER_PASSWORD}}"

  OSD-Functional-Test-AD:
    uses: ./.github/workflows/reusable-function-test-template.yml
    with:
      test-name: AD
      test-command: yarn cypress run --spec "cypress/integration/playground/plugins/playground_ad*.js" --config "baseUrl=${{inputs.endpoint}}" --env "openSearchUrl=${{inputs.endpoint}},SECURITY_ENABLED=true,username=${{secrets.OSD_USER}},password=${{secrets.OSD_USER_PASSWORD}}"


  OSD-Functional-Test-Alert:
    uses: ./.github/workflows/reusable-function-test-template.yml
    with:
      test-name: Alert
      test-command: yarn cypress run --spec "cypress/integration/playground/plugins/playground_alert*.js" --config "baseUrl=${{inputs.endpoint}}" --env "openSearchUrl=${{inputs.endpoint}},SECURITY_ENABLED=true,username=${{secrets.OSD_USER}},password=${{secrets.OSD_USER_PASSWORD}}"


  OSD-Functional-Test-Notifications:
    uses: ./.github/workflows/reusable-function-test-template.yml
    with:
      test-name: Notifications
      test-command: yarn cypress run --spec "cypress/integration/playground/plugins/playground_notifications*.js" --config "baseUrl=${{inputs.endpoint}}" --env "openSearchUrl=${{inputs.endpoint}},SECURITY_ENABLED=true,username=${{secrets.OSD_USER}},password=${{secrets.OSD_USER_PASSWORD}}"

  OSD-Functional-Test-Reports:
    uses: ./.github/workflows/reusable-function-test-template.yml
    with:
      test-name: Reports
      test-command: yarn cypress run --spec "cypress/integration/playground/plugins/playground_reports*.js" --config "baseUrl=${{inputs.endpoint}}" --env "openSearchUrl=${{inputs.endpoint}},SECURITY_ENABLED=true,username=${{secrets.OSD_USER}},password=${{secrets.OSD_USER_PASSWORD}}"

  OSD-Functional-Test-Observability:
    uses: ./.github/workflows/reusable-function-test-template.yml
    with:
      test-name: Observability
      test-command: yarn cypress run --spec "cypress/integration/playground/plugins/playground_observability*.js" --config "baseUrl=${{inputs.endpoint}}" --env "openSearchUrl=${{inputs.endpoint}},SECURITY_ENABLED=true,username=${{secrets.OSD_USER}},password=${{secrets.OSD_USER_PASSWORD}}"


  OSD-Functional-Test-IndexMan:
    uses: ./.github/workflows/reusable-function-test-template.yml
    with:
      test-name: IndexMan
      test-command: yarn cypress run --spec "cypress/integration/playground/plugins/playground_index*.js" --config "baseUrl=${{inputs.endpoint}}" --env "openSearchUrl=${{inputs.endpoint}},SECURITY_ENABLED=true,username=${{secrets.OSD_USER}},password=${{secrets.OSD_USER_PASSWORD}}"

