name: OpenSearch and Dashboards Deployment

on:
  workflow_call:
    inputs:
      helm-repo:
        required: true
        type: string
    secrets:
      access-key-id:
        required: true
      secret-access-key:
        required: true
      region:
        required: true
      kube-config:
        required: true

jobs:

  OS-OSD-Deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Step 1 - Dev - Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.access-key-id }}
          aws-secret-access-key: ${{ secrets.secret-access-key }}
          aws-region: ${{ secrets.region }}

      - name: Step 2 - Dev - Deploy OpenSearch and OpenSearch Dashboards By Helm Chart
        uses: elastic-analytics/dashboards-action@main
        env:
          KUBE_CONFIG_DATA: ${{ secrets.kube-config }}
        with:
          plugins: "" # optional, list of Helm plugins. eg. helm-secrets or helm-diff.
          # lists couple helm and kubetl commands here as placeholder, will add more
          # detail deployment command when helm configuration file ready.
          command: |
            helm repo add opensearch ${{ inputs.helm-repo }}
            helm repo update
            helm search repo opensearch